### ISSUE TITLE
feat: command should have `-v` or `--verbose` argument

### ISSUE THREAD

**Issue by pruthvi145** [merberich/teachable_dl#5]
Sometimes, we needed to see the progress that how much content is downloaded and how much is left. It is good to see the log of the downloaded content so we can track the process.

### Current Behaviour:
Currently, when we run the script, It starts downloading and shows that `Fetching course url` but we can not see that it is actually downloading or just stuck because of some issue.

### Possible Solution:
We can log the progress of `courses -> modules -> lessons` when we pass `-v` or `--verbose` argument in the run command.
for example:
```bash
Fetching course url: 'https://courses.data36.com/courses/enrolled/455539'
Downloading course: 'How to Become a Data Scientist'
 |
 |- Downloading module: 'INTRO'
     |- Downloading lesson: 'Preview01 - Welcome - the goal of this course'
     |- Downloading lesson: ' Preview02 - About me'
     ...

 |- Downloading module: ' MODULE #1: What you need to learn and why?'
 |- Downloading module: 'MODULE #2: Your step by step learning plan'
 ...

```

**Comment by merberich** [comment]
Resolved in 21ef139, thanks for the suggestion

**Comment by pruthvi145** [comment]
Thanks! can you also update `README.md` for the same?

**Comment by merberich** [comment]
Ah, whoops, done - b3d8004
